pipeline:
  name: test
  identifier: test
  projectIdentifier: Harness_Split
  orgIdentifier: PROD
  properties:
    ci:
      codebase:
        connectorRef: splitio
        repoName: split-openfeature-provider-web-js
        build:
          type: branch
          spec:
            branch: <+input>
  stages:
    - stage:
        name: CI Stage
        identifier: ci_stagex
        type: CI
        spec:
          cloneCodebase: true
          runtime:
            type: Cloud
            spec:
              size: small
          platform:
            os: Linux
            arch: Amd64
          execution:
            steps:
              - step:
                  type: Run
                  name: Setup NodeJS
                  identifier: setup_nodejs
                  spec:
                    connectorRef: account.harnessImage
                    image: ubuntu:24.04
                    shell: Bash
                    command: |-
                      echo "Installing Node.js version <+matrix.nodeVersion>"
                      apt-get update
                      apt-get install -y curl
                      curl -fsSL https://deb.nodesource.com/setup_<+matrix.nodeVersion>.x | bash -
                      apt-get install -y nodejs
                  timeout: 10m
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: install_dependencies
                  spec:
                    shell: Bash
                    command: |
                      # Set up npm cache directory
                      mkdir -p ~/.npm

                      # Run npm ci with cache enabled
                      npm ci
                    envVariables:
                      npm_config_cache: ~/.npm
                  timeout: 10m
              - step:
                  type: Run
                  name: Run Checks
                  identifier: run_checks
                  spec:
                    shell: Bash
                    command: |
                      npm run check
                  timeout: 10m
              - step:
                  identifier: run_tests
                  name: Run Tests
                  type: Test
                  timeout: 10m
                  spec:
                    command: |
                      npm run test
                    shell: Bash
                    connectorRef: account.harnessImage
                    image: ubuntu:24.04
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/test-results.xml"
                          - "**/junit-*.xml"
                    envVariables:
                      NODE_ENV: test
                      CI: "true"
