pipeline:
  name: test
  identifier: test
  projectIdentifier: Harness_Split
  orgIdentifier: PROD
  properties:
    ci:
      codebase:
        connectorRef: splitio
        repoName: split-openfeature-provider-web-js
        build: <+input>
  stages:
    - stage:
        name: CI Stage
        identifier: ci_stagex
        type: CI
        spec:
          cloneCodebase: true
          runtime:
            type: Cloud
            spec:
              size: small
              imageSpec:
                imageName: ubuntu-latest
          platform:
            os: Linux
            arch: Amd64
          execution:
            steps:
              - step:
                  type: Run
                  name: Setup NodeJS
                  identifier: setup_nodejs
                  spec:
                    uses: dcodeIO/setup-node-nvm@master
                    with:
                      node-version: 20
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: install_dependencies
                  spec:
                    shell: Bash
                    command: npm ci
              - step:
                  type: Run
                  name: Run Checks
                  identifier: run_checks
                  spec:
                    shell: Sh
                    command: npm run check
              - step:
                  identifier: run_tests
                  name: Run Tests
                  type: Test
                  spec:
                    command: npm run test
                    shell: Sh
                    connectorRef: account.harnessImage
                    image: ubuntu:24.04
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/test-results.xml"
                          - "**/junit-*.xml"
                    envVariables:
                      NODE_ENV: test
                      CI: "true"
